### PR TITLE
Implementing MSI packaging

### PR DESCRIPTION
**Pull request by winterheart**
Initial implementing of MSI packaging (issue #9).

Basic packaging done. Installer didn't actual work yet - it only installs DLL and Readme file. Not clear, how to implement starting - via Windows service or old Sheduler's task sequence. Need advise here.

Other things - WufucSetup creates two MSI for x86 and x64 (since it's impossible create universal installer), so there some basic checks - Installer checks platform and OS version. Quick fix check not yet implemented.

Installer should also autodetect previous version and seamless update it, but I not carefully checked it.

### CODE REVIEW

**Comment by zeffy** [comment]
Awesome so far, thanks for doing this!

>Not clear, how to implement starting - via Windows service or old Sheduler's task sequence. Need advise here.

Basically, for after-install tasks:
1. There is a task scheduler task `wufuc.xml` which should be imported by `schtasks /Create /XML "%INSTALLDIR%\wufuc.xml" /TN "wufuc.{72EEE38B-9997-42BD-85D3-2DD96DA17307}" /F`
2. By default, this task has the location of wufuc.dll set to `C:\Program Files\wufuc` so we must update it to wherever it was actually installed to: `schtasks /Change /TN "wufuc.{72EEE38B-9997-42BD-85D3-2DD96DA17307}" /TR "'%systemroot%\system32\rundll32.exe' """%INSTALLDIR%\wufuc.dll""",Rundll32Entry"`
3. Enable the task so it can be ran post-install `schtasks /Change /TN "wufuc.{72EEE38B-9997-42BD-85D3-2DD96DA17307}" /ENABLE`
4. Run wufuc `schtasks /Run /TN "wufuc.{72EEE38B-9997-42BD-85D3-2DD96DA17307}"`

For update pre-install tasks:
- Set the unload event to notify wufuc it should remove its hooks and shut down so that the files can be updated `rundll32 "%INSTALLDIR%\wufuc.dll",Rundll32Unload`

> Other things - WufucSetup creates two MSI for x86 and x64 (since it's impossible create universal installer), so there some basic checks - Installer checks platform and OS version. Quick fix check not yet implemented.

That's ok, I knew windows installer had this limitation. The Quick fix check is really more of a way to prevent people from installing wufuc when they don't actually need it. It doesn't break anything if you don't have a supported update, but it should keep people from installing it who might be confused about what it actually does. 

Another way this could be implemented is checking the version number of wuaueng.dll, I believe WiX supports doing this with existing files on install. Supported version numbers can be found in the [offsets doc](../blob/master/docs/Patch_Offsets.md).

The only other limitations I can think of right now is they must be limited to installing on

- Windows 7
- Windows 8.1
- Windows Server 2008 R2 
- Windows Server 2012 R2

**Comment by winterheart** [comment]
Hello.
Sorry for delay. Here last part of packaging - shedule task handling. I tested installing/uninstalling on my computer, looks fine. Still need heavy testing.

**Comment by zeffy** [comment]
Awesome! Thanks so much for doing this, I'll test it thoroughly and if it works correctly I will make sure it makes it into the next release.

**Comment by zeffy** [comment]
Hey @winterheart, I just wanted to let you know ahead of time that I'm going to be switching wufuc over to another installer platform called Advanced Installer (they decided to sponsor my project), however I really don't want you to think that I am unappreciative of the work you've put into the Wix installer.

What you had was excellent, and I'm very happy you took the time to contribute it! However, due to my own inexperience with Wix, I ended up spending too much time trying to add simple features to the installer or tweak settings rather than working on my actual project.

I hope this doesn't offend you in any way.

**Comment by winterheart** [comment]
OK, that sounds great. Looking forward for msi, I'm need it too :).

**Comment by zeffy** [comment]
I just released the new MSI installers for x64 and x86! https://github.com/zeffy/wufuc/releases :)

**Pull request merged**
